#!/bin/bash -e

#
# Copyright (C) 2004 Robin Rosenberg.
#
# This program is available under the terms of the GNU Public License.
#

while [ "${1:0:1}" = "-" ]
do
	case "$1" in
	-*) 
	    FLAGS="$FLAGS $1";
	    shift 1
	    ;;
	esac
done

if [ "$OS" = "Windows_NT" ];then sep=";";else sep=":";fi

mkdir -p $HOME/.jev
if [ ! -f $HOME/.jev/stdimport ]
then
    cat >$HOME/.jev/stdimport <<EOF
import java.io.*;
import java.util.*;
import java.awt.*;
import javax.swing.*;
import java.net.*;
import java.nio.*;
EOF
fi
cp=
if [ -f $HOME/.jev/stdclasspath ]
then
    while read p
    do
	cp="$cp${sep}$p"
    done < $HOME/.jev/stdclasspath
fi

TMP=${TMP:-/tmp}
class=jev$$
tmpf=$TMP/${class}.java
tmpx="$TMP/${class}.class $TMP/${class}\$*.class"
trap "cat $tmpf;rm -f $tmpf $tmpfx" 0
cat >$tmpf <$HOME/.jev/stdimport
cat >>$tmpf <<EOF
public class $class {
EOF

while [ $# -gt 1 ]
do
    echo >>$tmpf "$1"
    shift 1
done

cat >>$tmpf <<EOF
public static void main(String[] args) throws Throwable
{
	$1;
}
}
EOF
javac -d $TMP -cp "$cp$sep$TMP" $tmpf
time java -cp "$cp$sep$TMP" $class
if [ ! -f $TMP/${class}.class  ]
then
    cat $tmpf
fi

rm -f $(echo $tmpx)
